-- Generated by Monique - https://github.com/ToRvaLDz/monique

hl.monitor({
  output = "desc:AU Optronics 0x9AA2",
  mode = "3840x2160@60.002",
  position = "2241x1440",
  scale = 2,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Samsung Electric Company LC32G5xT HNTT800034",
  mode = "2560x1440@144",
  position = "1920x0",
  scale = 1,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.config({
  cursor = { default_monitor = "desc:Samsung Electric Company LC32G5xT HNTT800034" },
})
