const PREFIX_MAP = {
  us: 'User Story',
  bug: 'Bug',
  task: 'Task',
  feature: 'Feature'
};

const AZDO_URL_PATTERN = /\/(_workitems\/edit|_workitems\/edit\/)(\d+)/;
const PREFIXED_PATTERN = /^([a-zA-Z]+)#(\d+)$/;
const HASH_PATTERN = /^#(\d+)$/;
const PLAIN_NUMBER_PATTERN = /^(\d+)$/;

class AzdoClient {
  parseWorkItemId(input) {
    if (!input || typeof input !== 'string') {
      return null;
    }

    // Full AZDO URL
    const urlMatch = input.match(AZDO_URL_PATTERN);
    if (urlMatch) {
      return parseInt(urlMatch[2], 10);
    }

    // Prefixed: US#12345, Bug#67890, etc.
    const prefixMatch = input.match(PREFIXED_PATTERN);
    if (prefixMatch) {
      return parseInt(prefixMatch[2], 10);
    }

    // Hash prefix: #12345
    const hashMatch = input.match(HASH_PATTERN);
    if (hashMatch) {
      return parseInt(hashMatch[1], 10);
    }

    // Plain number: 12345
    const plainMatch = input.match(PLAIN_NUMBER_PATTERN);
    if (plainMatch) {
      return parseInt(plainMatch[1], 10);
    }

    return null;
  }

  parseWorkItemType(input) {
    if (!input || typeof input !== 'string') {
      return null;
    }

    const prefixMatch = input.match(PREFIXED_PATTERN);
    if (!prefixMatch) {
      return null;
    }

    const prefix = prefixMatch[1].toLowerCase();
    return PREFIX_MAP[prefix] || null;
  }

  extractRequirements(workItemFields) {
    if (!workItemFields || typeof workItemFields !== 'object') {
      throw new Error('workItemFields must be a non-null object');
    }

    const assignedTo = workItemFields['System.AssignedTo'];
    const tagsRaw = workItemFields['System.Tags'];

    return {
      title: workItemFields['System.Title'] || null,
      description: workItemFields['System.Description'] || null,
      acceptanceCriteria: workItemFields['Microsoft.VSTS.Common.AcceptanceCriteria'] || null,
      assignedTo: assignedTo
        ? (typeof assignedTo === 'string' ? assignedTo : assignedTo.displayName || null)
        : null,
      state: workItemFields['System.State'] || null,
      tags: tagsRaw
        ? tagsRaw.split(';').map(t => t.trim()).filter(Boolean)
        : [],
      priority: workItemFields['Microsoft.VSTS.Common.Priority'] || null,
      storyPoints: workItemFields['Microsoft.VSTS.Scheduling.StoryPoints'] || null
    };
  }

  formatForBootstrap(workItemId, workItemFields) {
    if (!workItemId) {
      throw new Error('workItemId is required');
    }
    if (!workItemFields || typeof workItemFields !== 'object') {
      throw new Error('workItemFields must be a non-null object');
    }

    const req = this.extractRequirements(workItemFields);

    const lines = [
      `# Work Item #${workItemId}: ${req.title || 'Untitled'}`,
      '',
      `**State:** ${req.state || 'Unknown'}  `,
      `**Priority:** ${req.priority || 'N/A'}  `,
      `**Story Points:** ${req.storyPoints || 'N/A'}  `,
      `**Assigned To:** ${req.assignedTo || 'Unassigned'}  `,
      `**Tags:** ${req.tags.length > 0 ? req.tags.join(', ') : 'None'}`,
      '',
      `## Description`,
      '',
      req.description || '_No description provided._',
      '',
      `## Acceptance Criteria`,
      '',
      req.acceptanceCriteria || '_No acceptance criteria provided._',
      '',
      `## Links`,
      '',
      `- [Azure DevOps Work Item](https://dev.azure.com/_workitems/edit/${workItemId}) *(update org/project in .sdlc.json)*`,
      '',
      `---`,
      `*Auto-generated by SDLC Framework Bootstrap*`
    ];

    return lines.join('\n');
  }

  buildMcpToolCall(workItemId) {
    if (!workItemId) {
      throw new Error('workItemId is required');
    }
    if (typeof workItemId !== 'number' || !Number.isInteger(workItemId) || workItemId < 1) {
      throw new Error('workItemId must be a positive integer');
    }

    return {
      tool: 'mcp__azure-devops__wit_get_work_item',
      params: { id: workItemId }
    };
  }
}

module.exports = AzdoClient;
